name: Release
run-name: ${{ github.actor }} is releasing 🚀
on: 
  push:
    tags:
      - '*'

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Decrypt developer key
        # see https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#storing-large-secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          INPUT: ./developer_key.gpg
          OUTPUT: ./developer_key
          PASSPHRASE: ${{ secrets.DEVELOPER_KEY_PASSPHRASE }}
      - name: Create release
        uses: blackshadev/garmin-connectiq-release-action@8.2.1
        with:
          projectJungle: ./monkey.jungle
          developerKey: ./developer_key
          outputPath: out/app.iq
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: garmin-home-assistant-${{ github.ref_name }}
          path: out/app.iq
