name: Translate
on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "resources/strings/strings.xml"
  #     - "translate.py"
  #     - "resources-*/strings/corrections.xml"

jobs:
  translate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4.7.1

      - run: |
          pip install google-genai beautifulsoup4 lxml

      - run: python translate.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          push_options: '--force'
